### ISSUE TITLE
Add progress bar

### ISSUE THREAD

**Issue by slhck** [slhck/ffmpeg-quality-metrics#12]
Use the function from https://github.com/slhck/ffmpeg-normalize/blob/master/ffmpeg_normalize/_cmd_utils.py#L45 to implement a progress bar with `tqdm`.

**Comment by CrypticSignal** [comment]
I've just implemented a progress bar for FFmpeg processes in my program which is similar to yours. It's similar to the implementation in ffmpeg-normalize but RegEx is not used. I'm sharing it as it might help:
https://github.com/CrypticSignal/video-quality-metrics/blob/master/ffmpeg_process_factory.py#L91

**Comment by slhck** [comment]
Thanks, good to know. I *guess* I will be re-using my own implementation since there are some differences in how I'd integrate it. I might even put this in a separate package for easier maintenance.
