### ISSUE TITLE
Docker build fails 

### ISSUE THREAD

**Issue by supriyaarun27** [slhck/ffmpeg-quality-metrics#17]
The docker build fails at **/bin/sh -c brew tap homebrew-ffmpeg/ffmpeg     && brew install homebrew-ffmpeg/ffmpeg/ffmpeg --with-libvmaf**

==> Tapping homebrew-ffmpeg/ffmpeg
Cloning into '/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew-ffmpeg/homebrew-ffmpeg'...
Tapped 1 formula (29 files, 198.7KB).
==> Installing ffmpeg from homebrew-ffmpeg/ffmpeg
==> Tapping linuxbrew/xorg
Cloning into '/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/linuxbrew/homebrew-xorg'...
Tapped 112 formulae (151 files, 1.7MB).
Error: No available formula with the name "linuxbrew/xorg/libxv" (dependency of homebrew-ffmpeg/ffmpeg/ffmpeg)
==> Searching for a previously deleted formula (in the last month)...
linuxbrew/xorg/libxv was deleted from linuxbrew/xorg in commit 8d4b5f8:
  xorg: migrate to homebrew-core
  See https://github.com/Homebrew/homebrew-core/pull/57995

To show the formula before removal run:
  git -C "$(brew --repo linuxbrew/xorg)" show 8d4b5f8^:Formula/libxv.rb

If you still use this formula consider creating your own tap:
  https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap
The command '/bin/sh -c brew tap homebrew-ffmpeg/ffmpeg     && brew install homebrew-ffmpeg/ffmpeg/ffmpeg --with-libvmaf' returned a non-zero code: 1
`

**Comment by slhck** [comment]
Thank you for raising this issue. It seems this has to do with homebrew-ffmpeg rather than this particular Dockerfile, but I will still investigate.

**Comment by slhck** [comment]
Closed in favor of https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/issues/52 – please follow this issue instead.

**Comment by slhck** [comment]
Note that I offer a more simplified Dockerfile now that does not depend on Homebrew.
