### ISSUE TITLE
[Bug] Dry-run still tries to process results

### ISSUE THREAD

**Issue by e-d-n-a** [slhck/ffmpeg-quality-metrics#20]
**When using the dry-run switch (-n) the processing of results isn't prevented and fails.**
_Numpy_ throws an error for me, when trying to work on an empty list in function "calculate_global_stats".

So, you should probably deactivate processing of results, when dry-run is activated [here](https://github.com/slhck/ffmpeg-quality-metrics/blob/e41bbaa4bca5425eba0a1265e0ea3d37539cd2b7/ffmpeg_quality_metrics/__main__.py#L440)!

**Comment by slhck** [comment]
I saw your changes in the proposed file but you were missing the `cli_args` part. I will follow a different approach, returning early from the main function.
