### ISSUE TITLE
Add support for multithreading

### ISSUE THREAD

**Issue by Sorkanius** [slhck/ffmpeg-quality-metrics#25]
Right now everything is exectued in a single thread, it would be very, very useful to have a parameter that let's you choose the number of threads in order to speed up the computations.

To be more speficic: 

Here: https://github.com/slhck/ffmpeg-quality-metrics/blob/master/ffmpeg_quality_metrics/__main__.py#L210

**Comment by slhck** [comment]
Can you please be more specific about what you need?

**Comment by Sorkanius** [comment]
That was quick. I updated the description.

**Comment by Sorkanius** [comment]
I created a PR with the suggested changes:

https://github.com/slhck/ffmpeg-quality-metrics/pull/26

**Comment by slhck** [comment]
This is now possible since v0.8.0.
