### ISSUE TITLE
Checking return code for error will not catch all possible errors

### ISSUE THREAD

**Issue by PolynomialDivision** [slhck/ffmpeg-quality-metrics#3]
Here the return code is checked.

https://github.com/slhck/ffmpeg-quality-metrics/blob/helper-script/ffmpeg_quality_metrics.py#L45

Unfortunately, ffmpeg does not signal every error in its standard configuration. You can add [extra flags](https://superuser.com/questions/588147/can-i-make-ffmpeg-stop-if-integrity-check-encounters-an-error), or check the stderr output. 
However, I'm not really sure how to do proper error handling in ffmpeg.

**Comment by slhck** [comment]
Are we expecting there to be such errors, or do you have an indication of this happening?
I've never really used these flags in practice, and I felt like I never needed them.

I guess that there *could* be decoding errors if one or more segments were not correctly encoded or the individual files are broken...
