### ISSUE TITLE
VMAF error on docker 

### ISSUE THREAD

**Issue by supriyaarun27** [slhck/ffmpeg-quality-metrics#34]
Hi, I am unable to evaluate the VMAF metrics using the docker option. This is the error I get : 

ERROR: General exception: error running command: ffmpeg -nostdin -nostats -y -threads 0 -r 25.0 -i tmp/ref-1280x720.mkv -r 25.0 -i tmp/dist-854x480.mkv -filter_complex '[1][0]scale2ref=flags=bicubic[dist][ref];[dist]setpts=PTS-STARTPTS[distpts];[ref]setpts=PTS-STARTPTS[refpts];[distpts]split=3[dist1][dist2][dist3];[refpts]split=3[ref1][ref2][ref3];[dist1][ref1]psnr='"'"'/tmp/q8dhlilg-psnr.txt'"'"';[dist2][ref2]ssim='"'"'/tmp/xuhto3nv-ssim.txt'"'"';[dist3][ref3]libvmaf='"'"'model_path=/ffmpeg_quality_metrics/vmaf_models/vmaf_v0.6.1.json:phone_model=0:log_path=/tmp/cy8ouo48-vmaf.txt:log_fmt=json:psnr=1:ssim=1:ms_ssim=1:n_threads=6'"'"'' -an -f null /dev/null
ffmpeg version N-57578-gab658db4d0-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      57.  0.100 / 57.  0.100
  libavcodec     59.  1.100 / 59.  1.100
  libavformat    59.  2.100 / 59.  2.100
  libavdevice    59.  0.100 / 59.  0.100
  libavfilter     8.  0.101 /  8.  0.101
  libswscale      6.  0.100 /  6.  0.100
  libswresample   4.  0.100 /  4.  0.100
  libpostproc    56.  0.100 / 56.  0.100
Input #0, matroska,webm, from 'tmp/ref-1280x720.mkv':
  Metadata:
    ENCODER         : Lavf58.20.100
  Duration: 00:00:00.12, bitrate: 526 kb/s
  Stream #0:0: Video: h264 (High 4:4:4 Predictive), yuv444p(progressive), 1280x720 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 1k tbn (default)
    Metadata:
      ENCODER         : Lavc58.35.100 libx264
      DURATION        : 00:00:00.120000000
Input #1, matroska,webm, from 'tmp/dist-854x480.mkv':
  Metadata:
    ENCODER         : Lavf58.20.100
  Duration: 00:00:00.12, bitrate: 444 kb/s
  Stream #1:0: Video: h264 (High 4:4:4 Predictive), yuv444p(progressive), 854x480 [SAR 1:1 DAR 427:240], 25 fps, 25 tbr, 1k tbn (default)
    Metadata:
      ENCODER         : Lavc58.35.100 libx264
      DURATION        : 00:00:00.120000000
Stream mapping:
  Stream #0:0 (h264) -> scale2ref:ref
  Stream #1:0 (h264) -> scale2ref:default
  psnr -> Stream #0:0 (wrapped_avframe)
  ssim -> Stream #0:1 (wrapped_avframe)
  libvmaf -> Stream #0:2 (wrapped_avframe)
Output #0, null, to '/dev/null':
  Metadata:
    encoder         : Lavf59.2.100
  Stream #0:0: Video: wrapped_avframe, yuv444p(tv, progressive), 1280x720 [SAR 1281:1280 DAR 427:240], q=2-31, 200 kb/s, 25 fps, 25 tbn
    Metadata:
      encoder         : Lavc59.1.100 wrapped_avframe
  Stream #0:1: Video: wrapped_avframe, yuv444p(tv, progressive), 1280x720 [SAR 1281:1280 DAR 427:240], q=2-31, 200 kb/s, 25 fps, 25 tbn
    Metadata:
      encoder         : Lavc59.1.100 wrapped_avframe
  Stream #0:2: Video: wrapped_avframe, yuv444p(tv, progressive), 1280x720 [SAR 1281:1280 DAR 427:240], q=2-31, 200 kb/s, 25 fps, 25 tbn
    Metadata:
      encoder         : Lavc59.1.100 wrapped_avframe
[Parsed_libvmaf_7 @ 0x6981240] libvmaf encountered an error, check log for details
Error while filtering: Invalid argument
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data for stream #0:0
[Parsed_ssim_6 @ 0x6980280] SSIM Y:0.934016 (11.805600) U:0.959752 (13.952503) V:0.942702 (12.418601) All:0.945490 (12.635218)
[Parsed_psnr_5 @ 0x697f300] PSNR y:18.595142 u:24.384397 v:21.387167 average:20.839158 min:20.833399 max:20.844925
Conversion failed!

I have also tested with videos that have the same resolution. I still get this error. Could you help out?

**Comment by supriyaarun27** [comment]
Hi, Thanks for getting back! 

I downloaded the latest version and tried again, I am getting the same error. 

After using the -k flag, I don't see the log file in the path specified in the ffmpeg command. 

Not sure if this helps, but this is the rest of the error I had not posted last time. 

(<class 'RuntimeError'>, RuntimeError('error running command: ffmpeg -nostdin -nostats -y -threads 0 -r 25.0 -i tmp/ref-1280x720.mkv -r 25.0 -i tmp/dist-854x480.mkv -filter_complex \'[1][0]scale2ref=flags=bicubic[dist][ref];[dist]setpts=PTS-STARTPTS[distpts];[ref]setpts=PTS-STARTPTS[refpts];[distpts]split=3[dist1][dist2][dist3];[refpts]split=3[ref1][ref2][ref3];[dist1][ref1]psnr=\'"\'"\'/tmp/i4gu55_9-psnr.txt\'"\'"\';[dist2][ref2]ssim=\'"\'"\'/tmp/0ilkyshs-ssim.txt\'"\'"\';[dist3][ref3]libvmaf=\'"\'"\'model_path=/ffmpeg_quality_metrics/vmaf_models/vmaf_v0.6.1.json:phone_model=0:log_path=/tmp/v_wj59kt-vmaf.txt:log_fmt=json:psnr=1:ssim=1:ms_ssim=1:n_threads=6\'"\'"\'\' -an -f null /dev/null\nffmpeg version N-57578-gab658db4d0-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2021 the FFmpeg developers\n  built with gcc 8 (Debian 8.3.0-6)\n  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg\n  libavutil      57.  0.100 / 57.  0.100\n  libavcodec     59.  1.100 / 59.  1.100\n  libavformat    59.  2.100 / 59.  2.100\n  libavdevice    59.  0.100 / 59.  0.100\n  libavfilter     8.  0.101 /  8.  0.101\n  libswscale      6.  0.100 /  6.  0.100\n  libswresample   4.  0.100 /  4.  0.100\n  libpostproc    56.  0.100 / 56.  0.100\nInput #0, matroska,webm, from \'tmp/ref-1280x720.mkv\':\n  Metadata:\n    ENCODER         : Lavf58.20.100\n  Duration: 00:00:00.12, bitrate: 526 kb/s\n  Stream #0:0: Video: h264 (High 4:4:4 Predictive), yuv444p(progressive), 1280x720 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 1k tbn (default)\n    Metadata:\n      ENCODER         : Lavc58.35.100 libx264\n      DURATION        : 00:00:00.120000000\nInput #1, matroska,webm, from \'tmp/dist-854x480.mkv\':\n  Metadata:\n    ENCODER         : Lavf58.20.100\n  Duration: 00:00:00.12, bitrate: 444 kb/s\n  Stream #1:0: Video: h264 (High 4:4:4 Predictive), yuv444p(progressive), 854x480 [SAR 1:1 DAR 427:240], 25 fps, 25 tbr, 1k tbn (default)\n    Metadata:\n      ENCODER         : Lavc58.35.100 libx264\n      DURATION        : 00:00:00.120000000\nStream mapping:\n  Stream #0:0 (h264) -> scale2ref:ref\n  Stream #1:0 (h264) -> scale2ref:default\n  psnr -> Stream #0:0 (wrapped_avframe)\n  ssim -> Stream #0:1 (wrapped_avframe)\n  libvmaf -> Stream #0:2 (wrapped_avframe)\nOutput #0, null, to \'/dev/null\':\n  Metadata:\n    encoder         : Lavf59.2.100\n  Stream #0:0: Video: wrapped_avframe, yuv444p(tv, progressive), 1280x720 [SAR 1281:1280 DAR 427:240], q=2-31, 200 kb/s, 25 fps, 25 tbn\n    Metadata:\n      encoder         : Lavc59.1.100 wrapped_avframe\n  Stream #0:1: Video: wrapped_avframe, yuv444p(tv, progressive), 1280x720 [SAR 1281:1280 DAR 427:240], q=2-31, 200 kb/s, 25 fps, 25 tbn\n    Metadata:\n      encoder         : Lavc59.1.100 wrapped_avframe\n  Stream #0:2: Video: wrapped_avframe, yuv444p(tv, progressive), 1280x720 [SAR 1281:1280 DAR 427:240], q=2-31, 200 kb/s, 25 fps, 25 tbn\n    Metadata:\n      encoder         : Lavc59.1.100 wrapped_avframe\n[Parsed_libvmaf_7 @ 0x65ed240] libvmaf encountered an error, check log for details

**Comment by slhck** [comment]
Are you on an operating system where you can try with a "plain" build of ffmpeg, so that we can make sure it's an issue with my Python script and not my tool?

For example, with the builds here: https://johnvansickle.com/ffmpeg/

Download [the model file](https://raw.githubusercontent.com/Netflix/vmaf/master/model/vmaf_v0.6.1.json) and save it somewhere next to the videos.

Then run:

```
/path/to/downloaded/ffmpeg \
    -r 24 -i ref-1280x720.mkv \
    -r 24 -i dist-854x480.mkv \
    -lavfi "[0:v]setpts=PTS-STARTPTS[reference]; \
            [1:v]scale=1280:720:flags=bicubic,setpts=PTS-STARTPTS[distorted]; \
            [distorted][reference]libvmaf=log_fmt=xml:log_path=/dev/stdout:model_path=vmaf_v0.6.1.json" \
    -f null -
```

Does this work?

I can also try myself if you can send me sample files that exhibit the problem.

**Comment by supriyaarun27** [comment]
I tried the static build on a Linux environment and I run into the same error. 

**1. Static build + ffmpeg_quality_metrics** 

ffmpeg_quality_metrics dist.mp4 ref.mp4 --metrics {vmaf,psnr,ssim} 
INFO: Writing temporary PSNR information to: /tmp/m4e4av3i-psnr.txt
INFO: Writing temporary SSIM information to: /tmp/uva14g_f-ssim.txt
INFO: Writing temporary VMAF information to: /tmp/ponimknu-vmaf.txt
INFO: Available filters: ['libvmaf', 'psnr', 'ssim', 'vif']
INFO: ffmpeg -nostdin -nostats -y -threads 0 -r 29.97 -i ref.mp4 -r 29.97 -i dist.mp4 -filter_complex '[1][0]scale2ref=flags=bicubic[dist][ref];[dist]setpts=PTS-STARTPTS[distpts];[ref]setpts=PTS-STARTPTS[refpts];[distpts]split=3[dist1][dist2][dist3];[refpts]split=3[ref1][ref2][ref3];[dist1][ref1]libvmaf='"'"'model_path=/home/jupyter-supriya/.local/lib/python3.7/site-packages/ffmpeg_quality_metrics/vmaf_models/vmaf_v0.6.1.json:phone_model=0:log_path=/tmp/ponimknu-vmaf.txt:log_fmt=json:psnr=1:ssim=1:ms_ssim=1:n_threads=6'"'"';[dist2][ref2]psnr='"'"'/tmp/m4e4av3i-psnr.txt'"'"';[dist3][ref3]ssim='"'"'/tmp/uva14g_f-ssim.txt'"'"'' -an -f null /dev/null
Traceback (most recent call last):
  File "/home/jupyter-supriya/.local/bin/ffmpeg_quality_metrics", line 8, in <module>
    sys.exit(main())
  File "/home/jupyter-supriya/.local/lib/python3.7/site-packages/ffmpeg_quality_metrics/__main__.py", line 128, in main
    ffqm.calc(metrics, vmaf_options=vmaf_options)
  File "/home/jupyter-supriya/.local/lib/python3.7/site-packages/ffmpeg_quality_metrics/ffmpeg_quality_metrics.py", line 287, in calc
    raise e
  File "/home/jupyter-supriya/.local/lib/python3.7/site-packages/ffmpeg_quality_metrics/ffmpeg_quality_metrics.py", line 283, in calc
    output = self._run_ffmpeg_command(filter_chains, desc=", ".join(metrics))
  File "/home/jupyter-supriya/.local/lib/python3.7/site-packages/ffmpeg_quality_metrics/ffmpeg_quality_metrics.py", line 504, in _run_ffmpeg_command
    _, stderr = run_command(cmd, self.dry_run, self.verbose)
  File "/home/jupyter-supriya/.local/lib/python3.7/site-packages/ffmpeg_quality_metrics/utils.py", line 80, in run_command
    f"error running command: {quoted_cmd(cmd)}\n{stderr.decode('utf-8')}"
RuntimeError: error running command: ffmpeg -nostdin -nostats -y -threads 0 -r 29.97 -i ref.mp4 -r 29.97 -i dist.mp4 -filter_complex '[1][0]scale2ref=flags=bicubic[dist][ref];[dist]setpts=PTS-STARTPTS[distpts];[ref]setpts=PTS-STARTPTS[refpts];[distpts]split=3[dist1][dist2][dist3];[refpts]split=3[ref1][ref2][ref3];[dist1][ref1]libvmaf='"'"'model_path=/home/jupyter-supriya/.local/lib/python3.7/site-packages/ffmpeg_quality_metrics/vmaf_models/vmaf_v0.6.1.json:phone_model=0:log_path=/tmp/ponimknu-vmaf.txt:log_fmt=json:psnr=1:ssim=1:ms_ssim=1:n_threads=6'"'"';[dist2][ref2]psnr='"'"'/tmp/m4e4av3i-psnr.txt'"'"';[dist3][ref3]ssim='"'"'/tmp/uva14g_f-ssim.txt'"'"'' -an -f null /dev/null
ffmpeg version N-57578-gab658db4d0-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      57.  0.100 / 57.  0.100
  libavcodec     59.  1.100 / 59.  1.100
  libavformat    59.  2.100 / 59.  2.100
  libavdevice    59.  0.100 / 59.  0.100
  libavfilter     8.  0.101 /  8.  0.101
  libswscale      6.  0.100 /  6.  0.100
  libswresample   4.  0.100 /  4.  0.100
  libpostproc    56.  0.100 / 56.  0.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'ref.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.77.100
  Duration: 00:00:24.39, start: 0.000000, bitrate: 826 kb/s
  Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 823 kb/s, 29.97 fps, 29.97 tbr, 11988 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
Input #1, mov,mp4,m4a,3gp,3g2,mj2, from 'dist.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.83.100
  Duration: 00:00:24.39, start: 0.000000, bitrate: 1756 kb/s
  Stream #1:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1280x720, 1753 kb/s, 29.97 fps, 29.97 tbr, 11988 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:0 (h264) -> scale2ref:ref
  Stream #1:0 (h264) -> scale2ref:default
  libvmaf -> Stream #0:0 (wrapped_avframe)
  psnr -> Stream #0:1 (wrapped_avframe)
  ssim -> Stream #0:2 (wrapped_avframe)
Output #0, null, to '/dev/null':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf59.2.100
  Stream #0:0: Video: wrapped_avframe, yuv420p(progressive), 1280x720, q=2-31, 200 kb/s, 29.97 fps, 29.97 tbn
    Metadata:
      encoder         : Lavc59.1.100 wrapped_avframe
  Stream #0:1: Video: wrapped_avframe, yuv420p(progressive), 1280x720, q=2-31, 200 kb/s, 29.97 fps, 29.97 tbn
    Metadata:
      encoder         : Lavc59.1.100 wrapped_avframe
  Stream #0:2: Video: wrapped_avframe, yuv420p(progressive), 1280x720, q=2-31, 200 kb/s, 29.97 fps, 29.97 tbn
    Metadata:
      encoder         : Lavc59.1.100 wrapped_avframe
[Parsed_libvmaf_5 @ 0x7b7e100] libvmaf encountered an error, check log for details
Error while filtering: Invalid argument
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data for stream #0:0
[Parsed_ssim_7 @ 0x7b80cc0] SSIM Y:0.959343 (13.908642) U:0.992666 (21.346651) V:0.993463 (21.846330) All:0.970584 (15.314092)
[Parsed_psnr_6 @ 0x7b80080] PSNR y:30.689484 u:44.301304 v:43.183993 average:32.343329 min:32.343329 max:32.343329
Conversion failed!

**2. Static build + command you mentioned (with model file downloaded) ** 

ffmpeg -r 24 -i ref-1280x720.mkv     -r 24 -i dist-854x480.mkv     -lavfi "[0:v]setpts=PTS-STARTPTS[reference]; \
            [1:v]scale=1280:720:flags=bicubic,setpts=PTS-STARTPTS[distorted]; \
            [distorted][reference]libvmaf=log_fmt=xml:log_path=/dev/stdout:model_path=vmaf_v0.6.1.json"     -f null -

ffmpeg version N-57578-gab658db4d0-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      57.  0.100 / 57.  0.100
  libavcodec     59.  1.100 / 59.  1.100
  libavformat    59.  2.100 / 59.  2.100
  libavdevice    59.  0.100 / 59.  0.100
  libavfilter     8.  0.101 /  8.  0.101
  libswscale      6.  0.100 /  6.  0.100
  libswresample   4.  0.100 /  4.  0.100
  libpostproc    56.  0.100 / 56.  0.100
Input #0, matroska,webm, from 'ref-1280x720.mkv':
  Metadata:
    ENCODER         : Lavf58.20.100
  Duration: 00:00:00.12, bitrate: 526 kb/s
  Stream #0:0: Video: h264 (High 4:4:4 Predictive), yuv444p(progressive), 1280x720 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 1k tbn (default)
    Metadata:
      ENCODER         : Lavc58.35.100 libx264
      DURATION        : 00:00:00.120000000
Input #1, matroska,webm, from 'dist-854x480.mkv':
  Metadata:
    ENCODER         : Lavf58.20.100
  Duration: 00:00:00.12, bitrate: 444 kb/s
  Stream #1:0: Video: h264 (High 4:4:4 Predictive), yuv444p(progressive), 854x480 [SAR 1:1 DAR 427:240], 25 fps, 25 tbr, 1k tbn (default)
    Metadata:
      ENCODER         : Lavc58.35.100 libx264
      DURATION        : 00:00:00.120000000
Stream mapping:
  Stream #0:0 (h264) -> setpts
  Stream #1:0 (h264) -> scale
  libvmaf -> Stream #0:0 (wrapped_avframe)
Press [q] to stop, [?] for help
Output #0, null, to 'pipe:':
  Metadata:
    encoder         : Lavf59.2.100
  Stream #0:0: Video: wrapped_avframe, yuv444p(tv, progressive), 1280x720 [SAR 1281:1280 DAR 427:240], q=2-31, 200 kb/s, 24 fps, 24 tbn (default)
    Metadata:
      encoder         : Lavc59.1.100 wrapped_avframe
Input model at vmaf_v0.6.1.json cannot be read successfully.=N/A speed=3.63x    
Caught VmafException: Error loading model (.pkl): Unknown token
[Parsed_libvmaf_3 @ 0x6a30780] libvmaf encountered an error, check log for details
Error while filtering: Invalid argument
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data for stream #1:0
Conversion failed! 


I have tried this with my own sample videos as well as the one you have provided in the test folder. The docker option was tested on both MacOS and a Linux environment.

**Comment by slhck** [comment]
Thank you for testing.

In this case though, please report at the official VMAF repo.

**Comment by slhck** [comment]
I just checked again and here you can see `Caught VmafException: Error loading model (.pkl): Unknown token
` — it assumes a PKL file, which is weird since you specified a JSON model. Perhaps this is a pointer to the real issue. And `Input model at vmaf_v0.6.1.json cannot be read successfully` also tells me that something is weird with the file.

I am a little bit confused because the Docker run with the test videos from this repo works perfectly here, so I am not sure where the difference would be.

**Comment by supriyaarun27** [comment]
I cross-checked the downloaded JSON file, and it looks fine. Not sure what the issue could be. 

It's also pretty strange that the docker option is not working, it used to work before. I have been using this previously as well.

**Comment by supriyaarun27** [comment]
`wget -q https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz ` in the docker file fetches the latest version of the git build, and that is the only possible aspect that could have been changed since it worked the last time for me. According to the date, it was last modified on 20th May. Both the tests I performed (docker + static build on my system) used this git master build. Could this be the problem?

**Comment by slhck** [comment]
Oh, interesting, now I run into the same issue! Thanks for pointing me to this.

I had tested it yesterday, but perhaps it was using an outdated download?

We could try the latest stable version to see if that fixes it. It could very well be that something in `libvmaf` was changed in the meantime that broke it.

**Comment by supriyaarun27** [comment]
I just tried older versions of the static build and that didn't seem to solve the issue either.

**Comment by slhck** [comment]
I'm reopening this for the time being.

**Comment by slhck** [comment]
I figured it out. The static builds provided on https://johnvansickle.com/ffmpeg/ seem to bundle libvmaf 1.x instead of 2.x. IIRC the builds already included 2.x at some point but now they don't?

Either way, the 1.x version of libvmaf does not support the JSON model files, and when you download the PKL model files from the VMAF repo, they don't work either.

So once you download the static build, try this:

```bash
ffmpeg_quality_metrics test/dist-854x480.mkv test/ref-1280x720.mkv -m vmaf --model-path ffmpeg-4.4-amd64-static/model/vmaf_v0.6.1.pkl
```

I will now have to check whether I can correctly identify the used version of libvmaf from ffmpeg …

**Comment by slhck** [comment]
Should be all fixed in v2.2.0.

**Comment by supriyaarun27** [comment]
Thank you!! It works now :)

**Comment by CrypticSignal** [comment]
> I figured it out. The static builds provided on https://johnvansickle.com/ffmpeg/ seem to bundle libvmaf 1.x instead of 2.x. IIRC the builds already included 2.x at some point but now they don't?

Interesting, I'll have to include the .pkl files in my program too, and edit the README to explaon the situation.
> I will now have to check whether I can correctly identify the used version of libvmaf from ffmpeg …

Let me know if you figure out how to do this.
