### ISSUE TITLE
Metrics for YUV

### ISSUE THREAD

**Issue by praneet195** [slhck/ffmpeg-quality-metrics#38]
Is there anyway to pass parameters like pix_fmt, resolution, rate and compute metrics for YUV?

**Comment by slhck** [comment]
This is not directly supported. You can wrap the YUV content in a Y4M or AVI container though.

**Comment by slhck** [comment]
Example:

    ffmpeg -r 60 -s 3840x2160 -pix_fmt yuv420p -i input.yuv output.y4m

**Comment by praneet195** [comment]
Hi,

please use -framerate, -video_size and -pixel_format instead of the other short parameters. This results in a psnr difference between the generated Y4m and yuv when it should be infinity. No idea why.

**Comment by slhck** [comment]
These are just different names for the same parameters. There is no difference between the generated Y4M files:

```
➜ ffmpeg -f lavfi -i testsrc=duration=10 -pix_fmt yuv420p -f rawvideo test.yuv
➜ ffmpeg -r 25 -s 320x240 -pix_fmt yuv420p -i test.yuv test1.y4m
➜ ffmpeg -framerate 25 -video_size 320x240 -pixel_format yuv420p -i test.yuv test2.y4m
➜ md5sum test1.y4m
247ef11b3d0fae6d9572c41d2eaa9071  test1.y4m
➜ md5sum test2.y4m
247ef11b3d0fae6d9572c41d2eaa9071  test2.y4m
```
