### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by bolognasammich** [slhck/ffmpeg-quality-metrics#53]
Hello,

I'm trying to run this command (python3 -m ffmpeg_quality_metrics) after cloning the repository through CLI. But when I try and run this command I get the following,

python3 -m ffmpeg_quality_metrics
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

I disabled the shortcut from the settings and then I get this error message,

python3 -m ffmpeg_quality_metrics
'python3' is not recognized as an internal or external command,
operable program or batch file.

Any idea what is causing the issue? Any help is appreciated.

Thanks!

**Comment by slhck** [comment]
Sorry, I cannot offer support for installing Python under Windows.

Please ask on https://superuser.com/ or other Q&A sites.

> run without arguments to install from the Microsoft Store

It seems like you need to enable the shortcut and just run `python` to install it.
