### ISSUE TITLE
File Location Question

### ISSUE THREAD

**Issue by bolognasammich** [slhck/ffmpeg-quality-metrics#55]
Hello,

I was able to get the program installed, but was wondering what folder I put videos in when running basic commands like ffmpeg-quality-metrics distorted.mp4 reference.avi

Any help is appreciated.

Thanks

**Comment by slhck** [comment]
I am not sure if I understand the question. On the command line, you should specify the absolute path to the file, wherever it is located on the file system.

So, for instance, it might be: `C:\SomeFolder\File.mp4`.

If you are new to the command line, I suggest to try a few tutorials first.

Alternatively, you may want to try the program FFMetrics, which offers a similar functionality in the GUI: https://github.com/fifonik/FFMetrics

**Comment by bolognasammich** [comment]
Oh, so it'd just be ffmpeg-quality-metrics C:\Rips\dist.mkv C:\Rips\ref.mkv

That's obvious in hindsight, sorry I am still learning lol.

Thank you for the help. I'll be sure to check out the link and a few tutorials!
