### ISSUE TITLE
Setting pnsr to full path on windows breaks ffmpeg

### ISSUE THREAD

**Issue by cdgriffith** [slhck/ffmpeg-quality-metrics#6]
```
ffmpeg_quality_metrics action.mkv Action-ultra.mkv -m action.mkv
[error] running command: ffmpeg -nostdin -y -threads 1 -i E:\Encoded\Action-ultra.mkv -i action.mkv -filter_complex [1][0]scale2ref=flags=bicubic[dist][ref];[dist]split[dist1][dist2];[ref]split[ref1][ref2];[dist1][ref1]psnr=C:\Users\me\AppData\Local\Temp\505ag31d-psnr.txt;[dist2][ref2]ssim=C:\Users\me\AppData\Local\Temp\13c5x9_e-ssim.txt -an -f null NUL

...

[psnr @ 000001ea3f8b4540] [Eval @ 000000a2711fe930] Undefined constant or missing '(' in 'UsersmeAppDataLocalTemp505ag31d-psnr.txt'
[psnr @ 000001ea3f8b4540] Unable to parse option value "UsersmeAppDataLocalTemp505ag31d-psnr.txt"
[psnr @ 000001ea3f8b4540] [Eval @ 000000a2711fe930] Undefined constant or missing '(' in 'UsersmeAppDataLocalTemp505ag31d-psnr.txt'
[psnr @ 000001ea3f8b4540] Unable to parse option value "UsersmeAppDataLocalTemp505ag31d-psnr.txt"
[psnr @ 000001ea3f8b4540] Error setting option stats_version to value UsersmeAppDataLocalTemp505ag31d-psnr.txt.
[Parsed_psnr_3 @ 000001ea3f8b4440] Error applying options to the filter.
[AVFilterGraph @ 000001ea3f863b40] Error initializing filter 'psnr' with args 'C:UsersmeAppDataLocalTemp505ag31d-psnr.txt'
Error initializing complex filters.
Invalid argument
```

Using ffmpeg version N-93103-gd20902fd23 on Windows 10. 

Changing `psnr=C:\Users\me\AppData\Local\Temp\505ag31d-psnr.txt` to `psnr=local_file.txt` worked fine. Adding quotes around the original path did not help.

**Comment by slhck** [comment]
Same comment as on the previous issue, I don't have Windows to test with. Do you think the path needs to be escaped when put into the FFmpeg filter?

**Comment by cdgriffith** [comment]
I found https://trac.ffmpeg.org/ticket/2166 

Meaning the path 

```C:\Users\me\AppData\Local\Temp\pc15hunr-psnr.txt```

needs transformed to: 

```c\\:/Users/me/AppData/Local/Temp/pc15hunr-psnr.txt```

(Tested working for me like this)

I would add a check of something like: 

```
if os.name == 'nt':
    temp_file_name_ssim = temp_file_name_ssim.replace("\\", "/").replace(":", "\\:")
    temp_file_name_psnr = temp_file_name_psnr.replace("\\", "/").replace(":", "\\:")
``

**Comment by slhck** [comment]
Thanks for the suggestion. I'll make a new release soon, currently traveling (I can however merge a PR quickly).

**Comment by cdgriffith** [comment]
Ran into issue with my idea above, as that would change the variable name throughout and wouldn't be usable for the program itself. Changed to just adding a wrapper around when they are inserted into the ffmpeg strings.

No rush on the PR, have working local stuff now :) 

Thanks for the fast replies!

**Comment by slhck** [comment]
Merged, thanks for the PR!
