### ISSUE TITLE
Unable to use CAMBI: error: unrecognized arguments: --vmaf-features cambi:full_ref=true

### ISSUE THREAD

**Issue by CKingX** [slhck/ffmpeg-quality-metrics#60]
I set up the git release essential in Windows and ran the command:
```ffmpeg_quality_metrics.exe distorted.mp4 original.mp4 -m vmaf --vmaf-features cambi:full_ref=true```
 I have the error of unrecognized argument for vmaf-features:
`ffmpeg_quality_metrics: error: unrecognized arguments: --vmaf-features cambi:full_ref=true`
 I then set up the Linux static ffmpeg build in WSL (OpenSUSE Leap) and followed the instructions again. I received the same error:
`ffmpeg_quality_metrics: error: unrecognized arguments: --vmaf-features cambi:full_ref=true`

I used the same example as on the README. Is this a bug or am I messing up the command?

**Comment by slhck** [comment]
Are you sure you are on the latest version of the pip package?

Note the warning in the readme:

> **Note:** Previous versions installed a `ffmpeg_quality_metrics` executable. To harmonize it with other tools, now the executable is called `ffmpeg-quality-metrics`. Please ensure you remove the old executable (e.g. run `which ffmpeg_quality_metrics` and remove the file).

**Comment by CKingX** [comment]
I uninstalled using pip uninstall ffmpeg-quality-metrics and I even looked for any ffmpeg-quality-metrics using the Everything app and couldn't find any remains. After running pip install ffmpeg-quality-metrics again, it installs ffmpeg_quality_metrics again. Is there a way to make pip install the newer version?

**Comment by slhck** [comment]
In that case please let me know your Python version and the installed package version. You need 3.8 or higher to get the latest version of this package.

**Comment by CKingX** [comment]
That explains it! Windows has Python 3.7.9 installed and OpenSUSE had python 3.6.15 installed. I will test after upgrading.

**Comment by CKingX** [comment]
It worked! Thank you!
