### ISSUE TITLE
 FfmpegQualityMetricsError: could not parse FPS from file 

### ISSUE THREAD

**Issue by kanlions** [slhck/ffmpeg-quality-metrics#61]
**:warning: Please read this carefully and edit the example responses! If you do not fill out this information, your bug report may be closed without comment.**

**Checklist** (please tick all boxes)
- [ ] I am using the latest version of `ffmpeg-quality-metrics` (run `pip3 install --upgrade ffmpeg-quality-metrics`)
- [ ] I am using the latest stable version of `ffmpeg` or a recent build from Git master
- [ ] Running from python
ffqm = FfmpegQualityMetrics('reference420.yuv', 'distorted420.yuv')

**Expected behavior**
Run error free
**Actual behavior**
 FfmpegQualityMetricsError: could not parse FPS from file 

**Command**
The exact command you were trying to run:
ffqm = FfmpegQualityMetrics('reference420.yuv', 'distorted420.yuv')
```
<enter command here>
```

Any output you get when running the command with the `-v` flag:

```
<add output here>
```

**Environment (please complete the following information):**
- [ ] Your operating system
- [ ] Ubuntu 22.04
- [ ] Your Python version / distribution (`python3 --version` or `python --version`)
- [ ] Your ffmpeg version (`ffmpeg -version`) ffmpeg version N-110062-g9413bdc381

**Comment by slhck** [comment]
This is more clearly explained now in the README as of 7b25fabdcc40f33731afaac2a6bd08f2a1873c41.

Using raw YUV files will now throw an error.

**Comment by kanlions** [comment]
Thank you for the help and apologies I missed the line in the manual regarding yuv. But the issues are not over yet 
I am getting the following error  when I run with .y4m
ffmpeg_quality_metrics.ffmpeg_quality_metrics.FfmpegQualityMetricsError: Your ffmpeg version does not have the filter 'libvmaf'

I verified while building ffmpeg that enable libvmaf 

See the ffmpeg -h
ffmpeg version N-110062-g9413bdc381 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.4.0-1ubuntu1~22.04)
  configuration: --enable-gpl --enable-libx264 --enable-libx265 --enable-nonfree --enable-libvmaf --enable-version3
  WARNING: library configuration mismatch
  avutil      configuration: --enable-pthreads --enable-pic --enable-shared --enable-rpath --arch=amd64 --enable-demuxer=dash --enable-libxml2 --enable-libvvdec --enable-libvvenc
  avcodec     configuration: --enable-pthreads --enable-pic --enable-shared --enable-rpath --arch=amd64 --enable-demuxer=dash --enable-libxml2 --enable-libvvdec --enable-libvvenc
  avformat    configuration: --enable-pthreads --enable-pic --enable-shared --enable-rpath --arch=amd64 --enable-demuxer=dash --enable-libxml2 --enable-libvvdec --enable-libvvenc
  avdevice    configuration: --enable-pthreads --enable-pic --enable-shared --enable-rpath --arch=amd64 --enable-demuxer=dash --enable-libxml2 --enable-libvvdec --enable-libvvenc
  avfilter    configuration: --enable-pthreads --enable-pic --enable-shared --enable-rpath --arch=amd64 --enable-demuxer=dash --enable-libxml2 --enable-libvvdec --enable-libvvenc
  swscale     configuration: --enable-pthreads --enable-pic --enable-shared --enable-rpath --arch=amd64 --enable-demuxer=dash --enable-libxml2 --enable-libvvdec --enable-libvvenc
  swresample  configuration: --enable-pthreads --enable-pic --enable-shared --enable-rpath --arch=amd64 --enable-demuxer=dash --enable-libxml2 --enable-libvvdec --enable-libvvenc
  libavutil      58.  5.100 / 58.  5.100
  libavcodec     60.  7.101 / 60.  7.101
  libavformat    60.  4.100 / 60.  4.100
  libavdevice    60.  2.100 / 60.  2.100
  libavfilter     9.  4.100 /  9.  4.100
  libswscale      7.  2.100 /  7.  2.100
  libswresample   4. 11.100 /  4. 11.100
  libpostproc    57.  2.100 / 57.  2.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Getting help:
    -h      -- print basic options
    -h long -- print more options
    -h full -- print all options (including all format and codec specific options, very long)
    -h type=name -- print all options for the named decoder/encoder/demuxer/muxer/filter/bsf/protocol

**Comment by slhck** [comment]
> Thank you for the help and apologies I missed the line in the manual regarding yuv

I only added the line after you posted, so you could not have known!
